name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "npm"

      - name: Ensure npm CLI Is Current
        run: |
          npm install -g npm@latest
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Check
        run: npm run check
